openapi: 3.0.3
info:
  title: ログイン・ログアウトAPI
  version: 0.1.0
  description: メールアドレスとパスワードによるログイン機能

paths:

# ========================================================================
# ログイン
# ========================================================================
  /auth/v1/login/:
    post:
      summary: アカウントログイン
      description: メールアドレスとパスワードでアカウントにログインします。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: "securePassword123"
      responses:
        '200':
          description: ログイン成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  login_token:
                    type: string
                    description: ログイントークンjwt
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

        '400':
          description: リクエスト形式の不備
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

        '401':
          description: 認証失敗（メールアドレスまたはパスワードが不正）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

# ========================================================================
# ログアウト
# ========================================================================
  /auth/v1/logout/:
    post:
      summary: アカウントログアウト
      description: アカウントをログアウトします。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - login_token
              properties:
                login_token:
                  type: string
                  description: ログイン時に発行されたトークン
                  example: "abcdef123456"

      responses:
        '204':
          description: アカウントログアウト成功

        '400':
          description: リクエスト形式の不備
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

        '401':
          description: 認証失敗
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: エラーコード
          example: "UNAUTHORIZED"
        message:
          type: string
          description: エラーの詳細内容
          example: "メールアドレスまたはパスワードが正しくありません。"